# MoonFRP Client Configuration for IP ending with 149
# Generated on Wed Jan 15 12:00:00 UTC 2025

# Server connection settings
serverAddr = "89.47.198.149"
serverPort = 7000

# Authentication
auth.method = "token"
auth.token = "12345678"

# Logging (optional)
log.to = "/var/log/frp/frpc_149.log"
log.level = "info"
log.maxDays = 7

[[proxies]]
name = "tcp-9005-149"
type = "tcp"
localIP = "127.0.0.1"
localPort = 9005
remotePort = 9005

[[proxies]]
name = "tcp-8005-149"
type = "tcp"
localIP = "127.0.0.1"
localPort = 54322
remotePort = 8005

[[proxies]]
name = "tcp-7005-149"
type = "tcp"
localIP = "127.0.0.1"
localPort = 54323
remotePort = 7005 